# Generated by Django 6.0.3 on 2026-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_weights', models.JSONField()),
                ('primary_muscles', models.JSONField()),
                ('equipment', models.JSONField()),
                ('type', models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation')], max_length=20)),
                ('pattern', models.CharField(max_length=50)),
                ('fatigue', models.FloatField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
