# Generated by Django 6.0.3 on 2026-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(db_index=True, max_length=100)),
                ('equipment', models.JSONField(default=list)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
