# Generated by Django 6.0.3 on 2026-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment', models.JSONField(default=list)),
                ('muscle_groups', models.JSONField(default=list)),
                ('no_of_exercises', models.IntegerField(default=0)),
                ('is_premade', models.BooleanField(default=True)),
                ('exercises', models.ManyToManyField(related_name='workouts', to='exercises.exercise')),
            ],
        ),
    ]
