# Generated by Django 6.0.3 on 2026-04-03 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_premade', models.BooleanField(default=False)),
                ('exercise_ids', models.JSONField()),
                ('muscle_groups', models.JSONField()),
                ('equipment', models.JSONField()),
                ('type', models.CharField(choices=[('hypertrophy', 'Hypertrophy'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('balanced', 'Balanced')], max_length=20)),
                ('total_fatigue', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
